### ISSUE TITLE
Add GEO power plant units data

### ISSUE THREAD

**Issue by FabianHofmann** [FRESNA/powerplantmatching#23]
The scraper https://morph.io/coroa/global_energy_observatory_power_plants also parses power plant unit data. PPM does not use this so far and misses a lot of data, e.g. Commissioning dates, number of units. 
In a first step: Integrate the data and use some of the data point.

**Comment by FabianHofmann** [comment]
TODO: Add a warning for custom config yaml, that the following snippet has to be added:

```yaml
GEO_units:
  net_capacity: false
  reliability_score: 3
  url: https://vfs.fias.science/f/3f4cc3876f/?raw=1
  fn: global_energy_observatory_ppl_units.csv
```
