### ISSUE TITLE
can't update / load inital 

### ISSUE THREAD

**Issue by vogt31337** [FRESNA/powerplantmatching#8]
Hi,

When trying:
```python
import powerplantmatching as pm
pm.collection.matched_data()
```

Running Windows 7, installed env with conda -f requirements.yaml

I get:
```
INFO:powerplantmatching.collection:Collect combined dataset for CARMA, ENTSOE, ESE, GEO, GPD, IWPDCY, OPSD
INFO:powerplantmatching.utils:Run process with 2 parallel threads.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\ppm\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Anaconda3\envs\ppm\lib\runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Anaconda3\envs\ppm\lib\pkgutil.py", line 462, in get_loader
    return find_loader(fullname)
  File "C:\Anaconda3\envs\ppm\lib\pkgutil.py", line 472, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Anaconda3\envs\ppm\lib\pkgutil.py", line 428, in iter_importers
    __import__(pkg)
  File "update_all_matches.py", line 13, in <module>
    update=True, use_saved_aggregation=True, use_saved_matches=False)
  File "powerplantmatching\collection.py", line 177, in matched_data
    matched = collect(matching_sources, **collection_kwargs)
  File "powerplantmatching\collection.py", line 100, in collect
    dfs = parmap(df_by_name, datasets)
  File "powerplantmatching\utils.py", line 320, in parmap
    p.start()
  File "C:\Anaconda3\envs\ppm\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Anaconda3\envs\ppm\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Anaconda3\envs\ppm\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 554, in save_tuple
    save(element)
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Anaconda3\envs\ppm\lib\pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function df_by_name at 0x000000000B6289E8>: it's not found as powerplantmatching.collection.df_by_name
```

conda list:

```
asn1crypto                0.24.0                py27_1003    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-fo
backports_abc             0.5                        py_1    conda-forge
basemap                   1.1.0                    py27_2    conda-forge
blas                      1.0                         mkl
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py27_1000    conda-forge
cffi                      1.11.5          py27h0c8e037_1001    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
colorama                  0.4.0                      py_0    conda-forge
cryptography              2.3.1            py27hc64555f_0    conda-forge
cryptography-vectors      2.3.1                 py27_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
freetype                  2.9.1             hf819b56_1004    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.2.0                 py27_1000    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopy                     1.17.0                     py_0    conda-forge
geos                      3.5.1                     vc9_1  [vc9]  conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                      vc9_0  [vc9]  conda-forge
idna                      2.7                   py27_1002    conda-forge
intel-openmp              2019.0                      118
ipaddress                 1.0.22                     py_1    conda-forge
ipython                   5.8.0                    py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jpeg                      9b                        vc9_2  [vc9]  conda-forge
kiwisolver                1.0.1           py27hdc96acc_1002    conda-forge
libpng                    1.6.34                    vc9_0  [vc9]  conda-forge
matplotlib                2.2.3            py27h7423b85_0    conda-forge
mkl                       2019.0                      118
mkl_fft                   1.0.6                    py27_0    conda-forge
networkx                  2.2                        py_1    conda-forge
numpy                     1.15.4           py27hbe4291b_0
numpy-base                1.15.4           py27h2753ae9_0
openssl                   1.0.2o                    vc9_0  [vc9]  conda-forge
pandas                    0.23.4          py27h39f3610_1000    conda-forge
pathlib2                  2.3.2                 py27_1000    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5                 py27_1000    conda-forge
pip                       18.1                  py27_1000    conda-forge
powerplantmatching        0.10.0                    <pip>
prompt_toolkit            1.0.15                     py_1    conda-forge
pycountry                 18.5.26                   <pip>
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                py27_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.4                    py27_0    conda-forge
pyqt                      5.6.0            py27h4cbc711_7    conda-forge
pyshp                     2.0.0                      py_0    conda-forge
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h2880e7c_1004    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pyyaml                    3.13            py27h0c8e037_1001    conda-forge
qt                        5.6.2                     vc9_1  [vc9]  conda-forge
requests                  2.20.1                py27_1000    conda-forge
scandir                   1.9.0           py27h0c8e037_1000    conda-forge
scipy                     1.1.0            py27h2df7626_1
seaborn                   0.9.0                      py_0    conda-forge
setuptools                40.5.0                   py27_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
sip                       4.18.1           py27hc56fc5f_0    conda-forge
six                       1.11.0                py27_1001    conda-forge
statsmodels               0.9.0           py27h0c8e037_1000    conda-forge
tornado                   5.1.1           py27h0c8e037_1000    conda-forge
traitlets                 4.3.2                 py27_1000    conda-forge
urllib3                   1.23                  py27_1001    conda-forge
vc                        9                             0    conda-forge
vs2008_runtime            9.0.30729.6161                0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.32.2                   py27_0    conda-forge
win_inet_pton             1.0.1                    py27_2    conda-forge
win_unicode_console       0.5                   py27_1000    conda-forge
wincertstore              0.2                   py27_1002    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
yaml                      0.1.7                     vc9_0  [vc9]  conda-forge
zlib                      1.2.11                    vc9_0  [vc9]  conda-forge
```

config.yaml:
```yaml
# io config
entsoe_token: XXX
google_api_key: 
opsd_vres_base_year: 2016

#matching config
# add a pandas query statement after the source name to filter the sources individually, e.g. - Carma: Fueltype=='Natural Gas'
# see http://pandas.pydata.org/pandas-docs/stable/indexing.html#the-query-method for info about query syntax
matching_sources:
    - CARMA
    - ENTSOE
    - ESE
    - GEO
    - GPD
    - IWPDCY
    - OPSD
    # - WEPP

fully_included_sources:
    - OPSD
    - ESE: Country not in ['Switzerland']
    - ENTSOE: Country not in ['Spain', 'Switzerland']
    - CARMA: Country == 'France' and Fueltype == 'Hydro'
    # - IWPDCY: lat == lat and Country == 'Sweden'

parallel_duke_processes: true
process_limit: 2

#data config
display_net_caps: true
remove_missing_coords: true
target_columns:
    - Name
    - Fueltype
    - Technology
    - Set
    - Country
    - Capacity
#    - Efficiency
    - Duration
    - YearCommissioned
    - Retrofit
    - lat
    - lon
    - File
    - projectID
target_countries:
#    - Austria
#    - Belgium
#    - Bulgaria
#    - Croatia
#    - Czech Republic
#    - Denmark
#    - Estonia
#    - Finland
#    - France
    - Germany
#    - Greece
#    - Hungary
#    - Ireland
#    - Italy
#    - Latvia
#    - Lithuania
#    - Luxembourg
#    - Netherlands
#    - Norway
#    - Poland
#    - Portugal
#    - Romania
#    - Slovakia
#    - Slovenia
#    - Spain
#    - Sweden
#    - Switzerland
#    - United Kingdom
target_fueltypes:
    - Bioenergy
    - Geothermal
    - Hard Coal
    - Hydro
    - Lignite
    - Natural Gas
    - Nuclear
    - Oil
    - Other
    - Solar
    - Waste
    - Wind
target_sets:
    - CHP
    - PP
    - Stores
target_technologies:
    - CCGT
    - OCGT
    - Steam Turbine
    - Combustion Engine
    - Run-Of-River
    - Pumped Storage
    - Reservoir
    - Marine
    - Onshore
    - Offshore
    - PV
    - CSP

# Allowed countries for matches of only CARMA and GEO
CARMA_GEO_countries:
#    -  Austria
#    -  Belgium
#    -  Bulgaria
#    -  Croatia
#    -  Denmark
#    -  Estonia
#    -  France
    -  Germany
#    -  Ireland
#    -  Italy
#    -  Luxembourg
#    -  Netherlands
#    -  Romania
#    -  Slovakia
#    -  Sweden
    
# heuristic config
fuel_to_lifetime:
    Bioenergy: 20
    Geothermal: 15
    Hard Coal: 45
    Hydro: 100
    Lignite: 45
    Natural Gas: 40
    Nuclear: 50
    Oil: 40
    Other: 5
    Solar: 25
    Waste: 25
    Wind: 25

# plotting config
fuel_to_color:
    OCGT: darkorange
    Hydro: royalblue
    Run-of-river: navy
    Ror: navy
    Lignite: orangered
    Nuclear: yellow
    Solar: gold
    Windoff: cornflowerblue
    Windon: steelblue
    Offshore: cornflowerblue
    Onshore: steelblue
    Wind: steelblue
    Bioenergy: g
    Natural Gas: firebrick
    CCGT: firebrick
    Coal: k
    Hard Coal: dimgray
    Oil: darkgreen
    Other: silver
    Waste: grey
    Geothermal: orange
    Battery: purple
    Hydrogen Storage: teal
    Electro-mechanical: teal
    Total: gold
```
